# Docker Compose is a tool for defining and running multi-container applications

# This file will setup WordPress, MySQL and PHPMyAdmin with a single command.
# To run --> docker compose up -d
# To tear down --> docker compose down --volumes 

version: '3.1'

services:
  # Database
  db: 
    image: mysql:latest
    # To persist our database we use volumes
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    # Database environment variabels
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    # Our Docker network that all our services run on
    networks:
     - wpsite

  # phpmyadmin (username: root, password: password)
  phpmyadmin:
    depends_on:
     - db
    image: phpmyadmin:latest
    restart: always
    # Map ports to access this from our local machine
    ports:
      - '8080:80' # We need port 8080 on our local machine to listen to port 80 on the container
    # phpmyadmin environment variabels
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - wpsite

  # Wordpress
  wordpress: 
    depends_on: 
     - db
    image: wordpress:latest # Uses Apache 
    # We need to map ports to access WordPress from our local machine
    ports:
      - '8000:80' # We need port 8000 on our local machine to listen to port 80 on the container
    restart: always
    # We need to map the WordPress files to show up in our root folder
    volumes: ['./:/var/www/html'] # This is the Web root for Apache where the WordPress files are stored
    # WordPress environment variabels
    environment: 
      WORDPRESS_DB_HOST: db:3306 # Default port for MySQL
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wpsite

# Map the volume of db_data and the network of wpsites
networks:
  wpsite:
volumes:
  db_data: